# Generated by Django 2.2.1 on 2019-05-15 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please, enter the phone number in a correct format.', regex='^\\+?1?\\d{9,15}$')])),
                ('language', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
