# Generated by Django 2.2.1 on 2019-05-16 15:06

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_servicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='polygon',
            field=djgeojson.fields.PolygonField(blank=True, default=dict),
        ),
    ]
